### ISSUE TITLE
email recovery issue with certain attached files => Special Characters in file name ? / Special encoding character file ?

### ISSUE THREAD

**Issue by Phil12n** [christianbur/getmail#18]
Hi,

I've been using getmail for at least one year and it does the job except when I receive certain emails with files attached.
I thought this was due to the size of the attached files, but that's not the case.

So I tried to analyze this problem differently and each time there is at least one attached file (pdf or zip or pptx...) and I suspect a problem with special characters like accents i.e. é. è [blank space]... used directly in the attached filename and/or the encoding character file used : recovery most often fails with Unix LF ANSI or Macintosh CR ANSI files while it seems to work better with Unix LF UTF8.

When this hangs, I move all pending emails from the inbox to a subfolder in the ISP's webmail client, then put all emails back into the inbox except the email with the problematic attachment, and getmail works instantly!

When I replace the first unrecovered email with getmail (the one that blocked the system) in the ISP webmail inbox it blocks again !

Thank you in advance for your help in solving this problem which I think comes from character sets.

Phil

**Comment by christianbur** [comment]
Hi,
please check first if the following things are still in your [docker-compose.yml](https://github.com/christianbur/getmail/commit/62bbc70ad9a9f5b2d34dfdd53b3576e0160a45fa)
   - mem_limit: 100m
   - mem_reservation: 20m

If this is the case, this could be responsible for the error. 

Email attachments are generally in [Mime format ](https://en.wikipedia.org/wiki/Email_attachment) and therefore Base64 encoded, so getmail should not see any special character at all. 
The problem is so individual that I can't analyze it without the email from you, can you forward the email to me?

**Comment by Phil12n** [comment]
Hi
Here is my docker-compose.yml :

```
version: '2.4'
services:

    getmail:
      image: cb/getmail
      build: ./Dockerfiles
      environment:
#        - TZ=${TZ}
        - TZ="Europe/Paris"
      volumes:
        - ./conf/settings.ini:/app/settings.ini:ro
      restart: always
      mem_limit: 100m
      mem_reservation: 20m
      networks:
        network-getmail:

#docker network create --driver=bridge --ipv6 --subnet=fdcb:9c90:23:11::/64 --gateway=fdcb:9c90:23:11::1 --subnet=172.23.11.0/24 --gateway=172.23.11.1 -o "com.docker.network.bridge.name"="br-getmail" network-getmail     
networks:
  network-getmail:
    external: true                

``` 
We talked about message size in a previous ticket "Maximum message size" but I really think that's not the case.

For information, I noticed a difference of -1 hour between the system date : date says Mon Jan 22 18:09:54 CET 2024 and getmail logs : /opt/getmail# docker-compose logs says getmail-getmail-1 | 2024-01-22 17:09:54... !

I tried to reinstall all getmail packages but I noticed that the repository was moved and https://github.com/christianbur/docker_projects#master in the latest docker-compose.yml is a broken link.

Anyway, if you want to test my issue, could you give me an email address? I can send you an email with a PDF attachment that blocks getmail from working.

Thank you for everything
Phil
